# sigma parameters
train_end: '2024-03-27'
test_start: '2024-03-28'
sigma_window: 1h
grid_frequency: 1s
half_life: 15min # originally 10 min
ewma_warmup: 3

# intensity / rate-parameter parameters
event_gap: 1ms
delta_min: 0.05 # tick size
delta_max: 50
delta_points: 30
slice_min: 0.1
slice_max: 5

# backtest parameters
A: 1.13
k: 0.47
gamma: 1.0e-3
tau: 430 # originally 300
quote_size: 0.01

# symmetric strategy parameterss
half_spread: 8.88