# sigma parameters
training_slice: '2024-03-27'
sigma_window: 1h
grid_frequency: 1s
half_life: 10min
ewma_warmup: 3

# intensity / rate-parameter parameters
event_gap: 1ms
delta_min: 0.05 # tick size
delta_max: 50
delta_points: 30
slice_min: 0.1
slice_max: 5

# backtest parameters
A: 1.13
k: 0.47
gamma: 10**-3
tau: 300