name: avellaneda-stoikov
channels:
  - defaults
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - ipykernel
  - pyyaml
  - pip
  - pip:
      - pyarrow